server:
  port: 20001
  servlet:
    session:
      timeout: 60000
    context-path: /yccloud

logging:
  level:
    root: info
    org:
      springframework:
        security:
          crypto: info
          authentication: debug
    com.yc: info
  file:
    path: ./log
    name: yccloud1.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/yccloud?serverTimezone=UTC
    username: root
    password: mufeng
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format-sql: true
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
#        generate_statistics: true
  profiles:
    active: @profiles.active@

hdfs:
  path: hdfs://yc/
  nameservices: yc
  username: root
  namenodes: nn1,nn2
  node1: node1:8020
  node2: node2:8020
  provider: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

#hdfs:
#  path: hdfs://106.12.129.165:8020/
#  nameservices: yc
#  username: root
#  namenodes: nn1,nn2
#  node1: node1:8020
#  node2: node2:8020
#  provider: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider


swagger:
  enable: true

